#!/bin/bash
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local && curl -s https://raw.githubusercontent.com/89luca89/distrobox/refs/heads/legacy/distrobox-create -o ~/.local/bin/distrobox-create && chmod +x ~/.local/bin/distrobox-create
